### ISSUE TITLE
[Feature Request] install it conditionally 

### ISSUE THREAD

**Issue by SamyPesse** [evanderkoogh/otel-cf-workers#20]
At the moment, it looks like it's impossible to conditionally instrument the worker (if a config prop is set), it makes it hard to disable it during tests with miniflare (also not sure it works with miniflare?)

**Comment by AdiRishi** [comment]
I think I have a pretty decent workaround for this.
I have the instrumentation code running everywhere (locally, in production and in Miniflare).
The telemetry data is only sent in production.

This is a snapshot of the important parts of my setup

`src/index.ts`
```ts
export type Env = {
  // the environment is passed in locally using .dev.vars or wrangler.toml
  ENVIRONMENT: 'development' | 'production';
  HONEYCOMB_API_KEY: string;
};

const handler = {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    return app.fetch(request, env, ctx);
  },
};

const otelConfig: ResolveConfigFn = (env: Env, _trigger) => {
  // IMPORTANT: during development or testing, this will be false
  const shouldSample = env.ENVIRONMENT === 'production';

  return {
    exporter: {
      url: 'https://api.honeycomb.io/v1/traces',
      headers: { 'x-honeycomb-team': env.HONEYCOMB_API_KEY },
    },
    service: { name: 'rest-api', version: env.GITHUB_SHA },
    sampling: {
      // by setting the ratio to 0, we effectively stop traces from being sent in development
      headSampler: { acceptRemote: true, ratio: shouldSample ? 0.5 : 0 },
    },
  };
};

export default instrument(handler, otelConfig);
```

**Comment by evanderkoogh** [comment]
There are some issues with some versions of wrangler where Miniflare blows up, but that should be fixed with the latest wrangler if I am not mistaken.

The challenge is that I can’t conditionally instrument things based on an environment setting is that I don’t get the environment until *after* I have instrumented the code.

My recommendation would be to run unit tests against your bare handler, not the instrumented one.

If you look at the example worker I have a handler.ts which exports the regular handler and then in index.ts I import that one and do all the configy bits in there.

But if you want to run your unit tests against the instrumented code, @AdiRishi seems to have that working too.

@AdiRishi, would you be able to write up that post into a “howto run this locally/in unit tests” doc?
That would be amazing.
